In [2]:
import numpy as np

In [5]:
# All 0s matrix
print(np.zeros((5)))
print(np.zeros((2,3,3)))

[0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [6]:
# All 1s matrix
print(np.ones((5), dtype='bool'))
print(np.ones((2,3,3)))

[ True  True  True  True  True]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [9]:
# Any other number (full_like)
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
b = np.full_like(a, 4)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [13]:
# Random decimal numbers
print(np.random.rand(4, 2))
print("Space between arrays")
print(np.random.random([4,2]))

[[0.16270604 0.65334215]
 [0.59990449 0.34988547]
 [0.30157781 0.11988935]
 [0.97983718 0.48749682]]
Space between arrays
[[0.91704625 0.13737549]
 [0.88054547 0.86537426]
 [0.51762455 0.09390751]
 [0.28867727 0.2522397 ]]


In [14]:
np.random.random_sample(a.shape)

array([[0.73334603, 0.54984924, 0.24961068, 0.1847081 , 0.27089706,
        0.01404582],
       [0.52724098, 0.96010959, 0.58764542, 0.92109161, 0.84350311,
        0.71058721]])

In [16]:
# Random Integer value
np.random.randint(-10,8, size=(2,4,5))

array([[[ -9,  -2,   5,  -5,  -7],
        [  5,   0,  -1,   7,  -8],
        [  1,  -3,  -5,   0,  -7],
        [ -7,  -7,   7,   1,   7]],

       [[ -1,   2,  -4,  -5,   5],
        [ -1,   4,   2,   1,  -2],
        [ -9,   6,   6,  -5,  -4],
        [-10,   7,   7,   0,  -8]]])

In [17]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [37]:
# Challenge array
"""
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1
"""
a = np.array([[1, 1, 1, 1, 1]])
a = np.repeat(a, 5, axis=0)
a[:, 1] = [1, 0, 0, 0, 1]
a[:, 2] = a[:, 1]
a[:, 3] = a[:, 1]
a[2, 2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
# Challenge array by Youtube presenter
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1, 1] = 9
print(z)
# Both ways of selecting the end column.
output[1:4, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)
# above shows b is referencing the same memory as a.  
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[100   2   3]
[1 2 3]


In [53]:
a = np.array([1,2,3,4])
print(a)
print(a + 2)
print(a - 2)
print(a * 2)
print(a % 2)
print(a / 2)
print(a ** 2)
b = np.array([1, 0, 1, 0])
print(a + b)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[1 0 1 0]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[2 2 4 4]


In [54]:
# Take the sine, cosine and tangent
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


Linear Algebra

In [58]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [67]:
c = np.identity(3)
print(c)
print(np.linalg.det(c))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


### Statistics

In [77]:
stats = np.array([[1,15,3], [4,5,6]])
stats

array([[ 1, 15,  3],
       [ 4,  5,  6]])

In [81]:
# smallest value in array
print(np.min(stats))
# largest value in array
print(np.max(stats))
# largest value per row
print(np.max(stats, axis=1))
# small value per column
print(np.min(stats, axis=0))
# sum of all value
print(np.sum(stats))

1
15
[15  6]
[1 5 3]
34


# Reorganizing Array

In [84]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [90]:
# Vertically stacking vectors
v1 = np.zeros(5)
v2 = np.ones(5)
v3 = np.vstack([v1, v2])
print(v3)
v4 = np.full((5), 4)
v3 = np.vstack([v1, v2, v4])
print(v3)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [4. 4. 4. 4. 4.]]


In [93]:
# Horizontal stack
v3 = np.hstack((v1, v4, v2))
v3

array([0., 0., 0., 0., 0., 4., 4., 4., 4., 4., 1., 1., 1., 1., 1.])

# Miscellaneous

Load Data From File

In [97]:
#pull data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Boolean Masking and Advanced Indexing

In [98]:
# print true false of each cell based on condition
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [99]:
# print value of each cell with a truthful result
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [100]:
## You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [101]:
# are any of the values in nth column across all rows 
# greater than 50?  
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [102]:
# are all of the values in the nth column greater than 50?
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [105]:
# true/false values being both greater than 50
# and less than 100 ... NOT!
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])