Initial info

In [1]:
import numpy as np
import sys

In [7]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get Dimension
a.ndim

1

In [10]:
# Get Shape
b.shape

(2, 3)

In [11]:
# Get Type
a.dtype

dtype('int16')

In [12]:
# Get Size
a.itemsize

2

In [17]:
# Get total size
print(a.nbytes)
print("Hi")
print(b.nbytes)

6
Hi
48


Accessing / Changing specific elements, rows, columns, etc

In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
# Get a specific element [row, column]
a[1, -3]

12

In [23]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [31]:
# Getting a little fancier [arrayIndex, ...
# startIndex:endIndex:stepSize]
a[1, 1:6:2]

array([ 9, 11, 13])

In [33]:
a[0, 1:-1:2]

array([2, 4, 6])

In [34]:
# Replace a specific cell's value
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [38]:
# Replace a column's value
a[:, 2] = [1, 63]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9 63 11 12 20 14]]


In [39]:
# 3-d example
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [42]:
# replace
b[:, 1, :] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
